apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: helmchart
    repoURL: 'https://github.com/miraccan00/djangoworkshop'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.dev.yaml  
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
